nameOverride: ""
fullnameOverride: ""

global:
  scope: ""
  image:
    registry: ""
    tag: ""

scope: Namespace
image:
  registry: ""
  repository: onosproject/core-operator
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

logging:
  loggers:
    root:
      level: info
      output:
        stdout:
          sink: stdout
  sinks:
    stdout:
      type: stdout
      stdout: {}
