apiVersion: config.onosproject.org/v1beta1
kind: Model
metadata:
  name: {{ template "stratum.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stratum.labels" . | nindent 4 }}
spec:
  plugin:
    type: stratum
    version: 1.0.0
  dependencies:
  - name: {{ template "openconfig.fullname" . }}
    namespace: {{ .Release.Namespace }}