apiVersion: config.onosproject.org/v1beta1
kind: Model
metadata:
  name: {{ template "openconfig.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openconfig.labels" . | nindent 4 }}
spec:
  type: openconfig
  version: 1.0.0
  dependencies:
  - name: {{ template "ietf.fullname" . }}
  modules:
  {{- range $path, $_  := $.Files.Glob "files/yang/*.yang" }}
  {{- $base := base $path }}
  {{- $names := split "@" $base }}
  {{- $name := $names._0 }}
  {{- $versions := split "." $names._1 }}
  {{- $version := $versions._0 }}
  - name: {{ $name | quote }}
    version: {{ $version | quote }}
    yangModule:
      data: |
{{ $.Files.Get $path | indent 8 }}
  {{- end }}