apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "onos-topo.fullname" . }}-config
  labels:
    app: {{ template "onos-topo.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  onos.yaml: |-
    atomix:
      controller: {{ .Values.store.controller }}
      namespace: {{ .Release.Namespace }}
      scope: {{ template "onos-topo.fullname" . }}
      protocols:
        consensus: {{ tpl (.Values.store.consensus.database | toString) $ }}
{{- if .Values.logging }}
    logging:
{{ toYaml .Values.logging | indent 6 }}
{{- end}}
