apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "core-operator.fullname" . }}-config
  labels:
    app: {{ template "core-operator.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  logging.yaml: |-
{{ toYaml .Values.logging | indent 4 }}