apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "core-operator.fullname" . }}-config
  labels:
    app: {{ template "core-operator.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  logging.yaml: |-
    loggers:
      root:
        level: debug
        output:
          stdout:
            sink: stdout
    sinks:
      stdout:
        type: stdout
        stdout: {}