apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.core.onosproject.org
spec:
  group: core.onosproject.org
  scope: Namespaced
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
    shortNames:
      - app
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - image
              properties:
                replicas:
                  type: integer
                  default: 1
                image:
                  type: string
                imagePullPolicy:
                  type: string
                  default: IfNotPresent
                model:
                  type: object
                  required:
                    - name
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                config:
                  type: object
                  additionalProperties:
                    type: string
            status:
              type: object
              properties:
                readyReplicas:
                  type: integer