# Default values for onos-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  image:
    registry: ""
    tag: ""
  store:
    consensus:
      name: ""
      image:
        registry: ""
        tag: ""

replicaCount: 1

image:
  registry: ""
  repository: onosproject/onos-config
  tag: v0.7.25
  pullPolicy: IfNotPresent
  pullSecrets: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "onos-config"

debug: false

devices: []

# Variable to change to onos topo service endpoint for the default onos-topo:5150
# topoEndpoint: onos-topo-classic:5150

plugin:
  cache:
    enabled: false
    storage:
      class: "standard"
      size: 1Gi
  compiler:
    version: v0.4.5
    target: ""

store:
  consensus:
    enabled: true
    name: ""
    image:
      registry: ""
      repository: atomix/atomix-raft-storage-node
      tag: v0.6.0
      pullPolicy: IfNotPresent
      pullSecrets: []
    clusters: 1
    replicas: 1
    partitions: 1
    persistence:
      storageClass: ""
      storageSize: 1Gi

service:
  type: ClusterIP

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config: {}

atomix:
  logging:
    loggers:
      root:
        level: info
        output:
          stdout:
            sink: stdout
    sinks:
      stdout:
        type: stdout
        stdout: {}

logging:
  loggers:
    root:
      level: info
      output:
        stdout:
          sink: stdout
  sinks:
    stdout:
      type: stdout
      stdout: {}

# Enable by giving a value like http://dex:32000
# make sure this is reachable at http://dex:32000/.well-known/openid-configuration
openidc:
  issuer:
  admingroup: AetherROCAdmin
