apiVersion: v2
name: topo-operator
version: 0.1.0
kubeVersion: ">=1.17.0"
appVersion: v0.6.18
description: µONOS Topology Operator
keywords:
  - onos
  - sdn
home: https://onosproject.org
maintainers:
  - name: ONOS Support
    email: support@opennetworking.org
