nameOverride: ""
fullnameOverride: ""

global:
  scope: ""
  image:
    registry: ""
    tag: ""

scope: Namespace
replicas: 1
image:
  registry: ""
  repository: onosproject/topo-operator
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

logging:
  loggers:
    root:
      level: info
      output:
        stdout:
          sink: stdout
  sinks:
    stdout:
      type: stdout
      stdout: {}
