apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ template "config-operator.fullname" . }}
  labels:
    app: {{ template "config-operator.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
  {{- $scope := include "core-operator.scope" . }}
  {{- if eq $scope "cluster" }}
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - config.onosproject.org
    resources:
      - '*'
    verbs:
      - '*'
  {{- end }}
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
    verbs:
      - '*'