apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "config-operator.fullname" . }}
  labels:
    app: {{ template "config-operator.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
webhooks:
- name: registry.config.onosproject.org
  rules:
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    scope: Namespaced
  clientConfig:
    service:
      name: {{ template "config-operator.fullname" . }}
      namespace: {{ .Release.Namespace }}
      path: /registry
  admissionReviewVersions: ["v1beta1"]
  sideEffects: None
  failurePolicy: Ignore
  timeoutSeconds: 10