{{- $scope := include "core-operator.scope" . }}
{{- if eq $scope "namespace" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: {{ template "config-operator.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - '*'
  - apiGroups:
      - config.onosproject.org
    resources:
      - '*'
    verbs:
      - '*'
{{- end }}